
char helptext[] = 
"~Up~,~Down~,~Left~,~Right~,~PgUp~,~PgDn~,~Home~,~End~ = Navigation\n"
"~'X'~ = Toggle 32-bit/64-bit address; ~'R'~ = Reload file data\n"
"~Tab~ = Select a file; Navigation keys only apply to selected file\n"
"~Ctrl~-~left~/~right~ = Change row width; ~Ctrl~-~up~/~down~ = Change row number\n"
"~Space~,~F6~ = Skip to next difference; any key = stop\n"
"~'+'~/~'-'~ = Change font size; ~Ctrl~-~'+'~/~'-'~ = Change font height\n"
"~Alt~-~'+'~/~'-'~ = Change font width; ~'C'~ = Change font\n"
"~Escape~ = Quit; ~'S'~= Save GUI config; ~'L'~ = Load config\n"
;
